//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Programa.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Can
    {
        public int IDCan { get; set; }
        public long DNIDueño { get; set; }
        public string NombreC { get; set; }
        public string RazaC { get; set; }
        public string CaracterC { get; set; }
        public string TamañoC { get; set; }
        public int VacunasC { get; set; }
        public System.DateTime NacimientoC { get; set; }
        public string DescripcionC { get; set; }
    
        public virtual Dueño Dueño { get; set; }
    }
}
