//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Programa.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dueño
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dueño()
        {
            this.Can = new HashSet<Can>();
            this.Solicitud = new HashSet<Solicitud>();
        }
    
        public long DNIDueño { get; set; }
        public string NombreD { get; set; }
        public string Apellido_MaternoD { get; set; }
        public string Apellido_PaternoD { get; set; }
        public long TelefonoD { get; set; }
        public string DistritoD { get; set; }
        public string DireccionD { get; set; }
        public string RefDirD { get; set; }
        public string CorreoD { get; set; }
        public System.DateTime NacimientoD { get; set; }
        public string GeneroD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Can> Can { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud> Solicitud { get; set; }
    }
}
