//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Programa.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Paseador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paseador()
        {
            this.Solicitud = new HashSet<Solicitud>();
        }
    
        public long DNIPaseador { get; set; }
        public string NombreP { get; set; }
        public string ApellidosP { get; set; }
        public string DistritoP { get; set; }
        public string CorreoP { get; set; }
        public string NacimientoP { get; set; }
        public string GeneroP { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Solicitud> Solicitud { get; set; }
    }
}
