//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Programa.Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        public int IDSolicitud { get; set; }
        public long DNIPaseador { get; set; }
        public long DNIDueño { get; set; }
        public decimal Monto { get; set; }
        public int Aceptacion { get; set; }
        public System.DateTime Fecha { get; set; }
        public System.TimeSpan Hora { get; set; }
        public string CodigoPago { get; set; }
    
        public virtual Dueño Dueño { get; set; }
        public virtual Paseador Paseador { get; set; }
    }
}
